name: phlox_animations
description: Flutter phlox_animations is a simple package to create beautiful custom animations .
  Animate multiple properties at once and  consists of several's feature.
version: 1.0.1
homepage: https://github.com/phloxCompany/flutter_phlox_animations.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  simple_animations: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
